version: "3"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${PG_DATABASE}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
    volumes:
      - ./migration/1.up.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $PG_USER -d $PG_DATABASE"]
      interval: 3s
      timeout: 5s
      retries: 5
      start_period: 1s
  
  service:
    build: .
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    
    

  